### ISSUE TITLE
counter 툴팁이 숨는 문제

### ISSUE THREAD

**Issue by gunlee01** [KIMSEONGSEOB/scouter-page#13]
툴팁이 다른 박스의 뒤쪽으로 그려집니다.

[Video link](https://youtu.be/blR8YJ_PypY)
[![Video Label](https://img.youtube.com/vi/blR8YJ_PypY/0.jpg)](https://youtu.be/blR8YJ_PypY)

**Comment by KIMSEONGSEOB** [comment]
수정했습니당
