### ISSUE TITLE
프로파일에 글자 잘림

### ISSUE THREAD

**Issue by gunlee01** [KIMSEONGSEOB/scouter-page#19]
* 각 step의 시간중 밀리세컨드 쪽이 좀 잘려서 나옴.
* THREAD CALL 스텝의 경우 스텝 제목이 길어서 잘림.

**Comment by gunlee01** [comment]
* 그리고 메시지가 긴 경우 MSG 태그가 왼쪽으로 밀림.

**Comment by KIMSEONGSEOB** [comment]
https://github.com/KIMSEONGSEOB/scouter-page/commit/df81d0a2f703186acf7d57d2e64656de2f1ac894
