### ISSUE TITLE
AIX 모니터링(토폴로지) 관련 질문 드립니다.

### ISSUE THREAD

**Issue by ssamsonn** [KIMSEONGSEOB/scouter-page#264]
안녕하세요.

모니터링 대상 서버 중 host가 AIX인 서버가 있어 해당 host의 obj_type=linux라고 호스트 에이전트 옵
션에 넣어 놓고 모니터링을 진행 중인데요..

해당 서버를 paper로 모니터링 하면 트랜잭션이 발생되어도 토폴로지가 그려지지 않는 이슈가 있어 문의 드립니다.

host는 AIX이고 was는 JEUS 입니다.

다른 카운터 정보들은 페이퍼에 잘 뜨고, 토폴로지만 안 그려지고 있습니다.

답변 부탁드립니다.

감사합니다,

**Comment by kranian** [comment]
scouter java agent 설정이 counter_interaction_enabled=true 인지 확인보시고, JEUS 내에 어플리케이션이 JDBC 연계 또는 외부 HTTP 연계가 한번이라도 호출되었다면 내용은 보이실겁니다.
