### ISSUE TITLE
XLOG가 잘려 나오는 현상이 있어 질문 드립니다

### ISSUE THREAD

**Issue by rornfdlek** [KIMSEONGSEOB/scouter-page#266]
안녕하세요.
PAPER 화면에서 처음 렌더링했을 때, 그리고 다른 탭으로 이동했다가 돌아오는 등 새로고침이 될 때  XLOG의 뒷부분 일부(1~30% 정도)만 정상적으로 출력이 되고 앞부분은 잘려 나오는 현상이 있어 질문 드립니다.
여러 서버에서 scouter server+webapp+paper 를 올려 테스트 해보았을 때, 일부 서버들에서 이런 현상이 있는데요..
분석해보니 정상적으로 XLOG가 출력되는 상황에서와 그렇지 않은 상황에서 getXLog()의 파라미터인 offset1, offset2가 형태가 좀 다르더라구요...
정상적으로 출력되는 경우, offset1이 0 또는 1이고 offset2만 늘거나 변화하는데,
그렇지 않은 경우는 offset1이 처음엔 0이었다가 바로 10664. 6249 등과 같은 큰 값이 들어가 있었습니다.
혹시 이 문제가 맞을까요?
이슈#193의 솔루션은 적용한 상황입니다.
답변 기다리겠습니다ㅜㅜ

**Comment by kranian** [comment]
소스를 확인해 보니깐 offset1과 offset2 는 XLOG를 가져오기 위한  간격 설정 파라미터가 맞습니다. 
처음 API로 데이터를 가져올때는 초기값으로 해당  파라미터가 offset1=0,offset2=0으로 설정 후 응답 값에서 offset1,offset2를 다음 데이터를 가져오는 파라미터로 설정  합니다. 

참고 소스 라인)
  -  https://github.com/scouter-contrib/scouter-paper/blob/master/src/components/Paper/Paper.js#L823

간단 하게는 정상과 비정상 출력되는  스카우터 버전을 비교 해주세요. 추가적으로 비정상 적으로 나오는 일부 서버에서의 서버 시간 설정을 확인주시고요

**Comment by rornfdlek** [comment]
답변 감사합니다.
정상과 비정상 출력되는 스카우터 버전은 같고 서버시간 설정도 동일하게 잘 되어 있습니다..
혹시 API의 result로 가져오는 offset1, offset2 이 정확히 각각 어떤 의미인지 알 수 있을까요?
offset1 : xlog loop / offset2 : xlog index
이렇게 나와 있는데, 조금 더 설명해주시면 감사하겠습니다ㅜㅜ
offset1을 아예 0으로 고정하면 문제가 해결이 되는 경우가 있는데 이래도 되는 건가 해서요..

**Comment by kranian** [comment]
답답하시겠지만 잠시만 기달려주세요. @gunlee01  건희님 ㅎㅎ 이거 설명 부탁드려도 될까요??

**Comment by gunlee01** [comment]
페이퍼의 리얼타임 XLOG는 최근 10분(또는 설정에 따라 5분)의 데이터를 표현해 줍니다.
해당 페이지 접근시 현재 시간부터 10분이전까지의 과거의 데이터를 서버에서 조회하여 표현하는데
무제한 건수를 가져오는 건 아니고 서버 부하 / 브라우저 부하를 고려하여 최근 10,000건의 XLOG만 가져와서 표현해 줍니다.
(1000TPS만 되어도 최근 10분이면 1000*60*10 = 600,000 건의 데이터의 조회가 필요합니다.)
그 이후에는 수초간 수집된 데이터를 지속적으로 조회해 기존 데이터에 Append 하여 화면에 보여주는 방식입니다. 
가져온 데이터의 이후 데이터를 가져오기 위해 이전 요청에서 응답받은 offset1, offset2를 스카우터로 전송합니다. 
offset값은 스카우터 서버에서 xlog를 관리하는 저장소의 offset 값입니다. 

조금 불편하겠지만 자주 페이지를 이동한다면 실시간 XLOG를 보여주는 브라우저는 유지하고 창을 하나 더 띠워서 사용하시는 것을 권장드립니다.
