### ISSUE TITLE
xlog 차트에서 error 토글 기능

### ISSUE THREAD

**Issue by gunlee01** [KIMSEONGSEOB/scouter-page#54]
error 토글시 error인 xlog만 보여주는 기능

**Comment by gunlee01** [comment]
@mindplates 
이거 필요합니다~

**Comment by mindplates** [comment]
@gunlee01 
필터 기능을 추가했습니다만, XLOG 점 데이터에서 입력된 URL 등을 HASH로 변경하는 부분이 추가되지 않아서, 현재는 HASH로만 검색되도록 development에 추가하였습니다.
해당 부분은 나중에 살펴본 후 개선하도록 하겠습니다.

**Comment by mindplates** [comment]
1.8 버전에 필터 기능 추가되었습니다.
