### ISSUE TITLE
초기 화면 로드시 10분 데이터 차트 이상

### ISSUE THREAD

**Issue by gunlee01** [KIMSEONGSEOB/scouter-page#9]
- HostAgent가 있는 경우 차트가 끊기게 그려지는 문제
- 끊긴 차트에서 마우스를 이리저리 움직이는 경우 CPU 과점, 다른 Route로 이동해도 CPU 해소되지 않음
- 이후 다시 돌아오면 인스턴스 선택이 초기화 되어 있음

**Comment by KIMSEONGSEOB** [comment]
수정
